#!/bin/bash

#This script can push a local wordpress site to jimmyweb staging automatically
echo -e "Step01. Name your site(e.g. xxx), prepare xxx.zip & xxx.sql, upload to /home/alex/ via ftp \n"
echo -e "Step02. Ssh to server (uesr alex) \n"
echo -e "Step03. Make sure you run 'sudo -s' first \n"
echo -e "Step04. Run ./create-new-site xxx \n"


echo -e "Step1. Create config file under /etc/httpd/sites-enabled \n"
echo -e "<VirtualHost *:80>\n" >> /etc/httpd/sites-enabled/$1.jimmystage2.com.conf
echo -e "ServerName $1.jimmystage2.com\n" >> /etc/httpd/sites-enabled/$1.jimmystage2.com.conf
echo -e "DocumentRoot /mnt/volume_sgp1_03/$1.jimmystage2.com/html\n" >> /etc/httpd/sites-enabled/$1.jimmystage2.com.conf
echo -e "<Directory \"/mnt/volume_sgp1_03/$1.jimmystage2.com/html\">\n" >> /etc/httpd/sites-enabled/$1.jimmystage2.com.conf
echo -e "AllowOverride All\n" >> /etc/httpd/sites-enabled/$1.jimmystage2.com.conf
echo -e "Options Indexes FollowSymLinks\n" >> /etc/httpd/sites-enabled/$1.jimmystage2.com.conf
echo -e "AuthType Basic\n" >> /etc/httpd/sites-enabled/$1.jimmystage2.com.conf
echo -e "AuthName \"Authorized personnel only.\"\n" >> /etc/httpd/sites-enabled/$1.jimmystage2.com.conf
echo -e "AuthUserFile /var/.jimmywebpass\n" >> /etc/httpd/sites-enabled/$1.jimmystage2.com.conf
echo -e "Require valid-user\n" >> /etc/httpd/sites-enabled/$1.jimmystage2.com.conf
echo -e "Order Deny,Allow\n" >> /etc/httpd/sites-enabled/$1.jimmystage2.com.conf
echo -e "Deny from all\n" >> /etc/httpd/sites-enabled/$1.jimmystage2.com.conf
echo -e "Allow from 203.219.232.158\n" >> /etc/httpd/sites-enabled/$1.jimmystage2.com.conf
echo -e "Allow from 110.143.200.96\n" >> /etc/httpd/sites-enabled/$1.jimmystage2.com.conf
echo -e "Allow from 203.206.217.123\n" >> /etc/httpd/sites-enabled/$1.jimmystage2.com.conf
echo -e "Allow from 220.233.16.176\n" >> /etc/httpd/sites-enabled/$1.jimmystage2.com.conf
echo -e "Satisfy Any\n" >> /etc/httpd/sites-enabled/$1.jimmystage2.com.conf
echo -e "</Directory>\n" >> /etc/httpd/sites-enabled/$1.jimmystage2.com.conf
echo -e "ErrorLog /mnt/volume_sgp1_03/$1.jimmystage2.com/log/error.log\n" >> /etc/httpd/sites-enabled/$1.jimmystage2.com.conf
echo -e "CustomLog /mnt/volume_sgp1_03/$1.jimmystage2.com/log/requests.log combined\n" >> /etc/httpd/sites-enabled/$1.jimmystage2.com.conf
echo -e "</VirtualHost>\n" >> /etc/httpd/sites-enabled/$1.jimmystage2.com.conf



echo -e "Step2. Create site folder under /var/sites/ \n"
mkdir /var/sites/$1.jimmystage2.com
mkdir /var/sites/$1.jimmystage2.com/html
mkdir /var/sites/$1.jimmystage2.com/log

echo -e "Step3. move zip file to /var/sites/ then unzip \n"
cp $1.zip /var/sites/$1.jimmystage2.com/html
cd /var/sites/$1.jimmystage2.com/html
unzip ./$1.zip
rm -fr ./$1.zip
cd

echo -e "Step4. Change owner of the site folder so that we can use ftp \n"
sudo chown -R alex /var/sites/$1.jimmystage2.com

echo -e "Step5. Change permission so that we can upload in wordpress \n"
sudo chmod -R 777 /var/sites/$1.jimmystage2.com/html/wp-content/uploads/



echo -e "Step6. Restart apache \n"
systemctl restart httpd.service



echo -e "Step7. Create new database \n"
mysql --defaults-file=/home/alex/mysql-opts --defaults-group-suffix=root -hlocalhost -P3306 -e "create database $1;"

echo -e "Step8. Create new database user \n"
mysql --defaults-file=/home/alex/mysql-opts --defaults-group-suffix=root -hlocalhost -P3306 -e "CREATE USER '$1'@'%' IDENTIFIED BY 'Gbc12356789$';"
mysql --defaults-file=/home/alex/mysql-opts --defaults-group-suffix=root -hlocalhost -P3306 -e "GRANT ALL PRIVILEGES ON $1.* TO '$1'@'%';"

echo -e "Step9. Import SQL  \n"
mysql --defaults-file=/home/alex/mysql-opts --defaults-group-suffix=root -hlocalhost -P3306 $1 < /home/alex/$1.sql


echo -e "Step10. update table wp-options  \n"
mysql --defaults-file=/home/alex/mysql-opts --defaults-group-suffix=root -hlocalhost -P3306 -e "UPDATE $1.wp_options SET option_value= 'http://$1.jimmystage2.com' WHERE option_name='siteurl';"
mysql --defaults-file=/home/alex/mysql-opts --defaults-group-suffix=root -hlocalhost -P3306 -e "UPDATE $1.wp_options SET option_value= 'http://$1.jimmystage2.com' WHERE option_name='home';"


echo -e "Step11. update wp-config.php  \n"
sed -i -e "s/define( 'DB_NAME', 'local' );/define( 'DB_NAME', '$1' );/g" /var/sites/$1.jimmystage2.com/html/wp-config.php
sed -i -e "s/define( 'DB_USER', 'root' );/define( 'DB_USER', '$1' );/g" /var/sites/$1.jimmystage2.com/html/wp-config.php
sed -i -e "s/define( 'DB_PASSWORD', 'root' );/define( 'DB_PASSWORD', 'Gbc12356789$' );/g" /var/sites/$1.jimmystage2.com/html/wp-config.php


echo -e "Step12. You may need to run better-search-replace plugin to replace the domain as well \n"